-- CREACIÓN DE USUARIO S
CREATE USER 'USUARIO_LECTURA'@'LOCALHOST' IDENTIFIED BY 'UsuarioLectura';
CREATE USER 'USUARIO_LIM'@'LOCALHOST' IDENTIFIED BY 'UsuarioLIM';

-- ASIGNACIÓN DE PERMISOS A USUARIOS
GRANT SELECT ON gimmnasio.* TO 'USUARIO_LECTURA'@'LOCALHOST';
GRANT SELECT,INSERT,UPDATE ON gimmnasio.* TO 'USUARIO_LIM'@'LOCALHOST';