insert into actividad  values (null,'YOGA');
insert into actividad  values (null,'MMA');
insert into actividad  values (null,'PILATES REFORMER');
insert into actividad  values (null,'MUSCULACION');
insert into actividad  values (null,'ZUMBA');
insert into actividad  values (null,'MINI TRAMP');
insert into alumnos  values (null,'MARIANO','FREIRES',28,'3512427078','FREIRESMARIANO@GMAIL.COM');
insert into alumnos  values (null,'ROCIO','DIAZ',26,'3512300221','DIAZRO96@GMAIL.COM');
insert into alumnos  values (null,'MARIANA','GABBANI',52,'3512457863','GABBANIMARIANA@GMAIL.COM');
insert into alumnos  values (null,'ROSSANA','OLMOS',55,'3512286363','OLMOSROSSANA12@GMAIL.COM');
insert into profesores  values (null,'OSCAR','FERNANDEZ','351785632','OSCARLARENGA56@GMAIL.COM','AVENIDA LA PATRIA 887 BARRIO SUIZO','20-27870963-8');
insert into profesores  values (null,'SOFIA','SOSA','351895632','OSCARLARENGA56@GMAIL.COM','LOS AROMOS 89 BARRIO JESUITA','27-37850654-7');
insert into profesores  values (null,'AGUSTIN','SANTANOCETO','351454982','LABALASANTONOCETO@GMAIL.COM','PUBLICA B 6105 BARRIO CARCANO','20-32456784-8');
insert into clases values (null,'MUSCULACION 1',4,3);
insert into clases values (null,'YOGA PARA ADULTOS',1,2);
insert into clases values (null,'ZUMBA',5,2);
insert into clasesalumnos values (null,1,1);
insert into clasesalumnos values (null,2,3);
insert into clasesalumnos values (null,2,4);
insert into clasesalumnos values (null,3,2);
